Repository meta-soul/MetaSpore, pull requests merged in 2022-05, with the labels that each got.

#84 update wheel release
  README-CN.md
  README.md
  docker/ubuntu20.04/Dockerfile_dev
  docker/ubuntu20.04/Dockerfile_training_release
Labels: documentation

#85 add k8s deployment with helm chart
  demo/movielens/online/src/main/resources/application.properties
  demo/movielens/online/src/main/resources/bootstrap.yml
  kubernetes/demo/movielens-chart/README-CN.md
  kubernetes/demo/movielens-chart/README.md
  kubernetes/demo/movielens-chart/chart/.helmignore
  kubernetes/demo/movielens-chart/chart/Chart.yaml
  kubernetes/demo/movielens-chart/chart/templates/_helpers.tpl
  kubernetes/demo/movielens-chart/chart/templates/deployment.yaml
  kubernetes/demo/movielens-chart/chart/templates/hpa.yaml
  kubernetes/demo/movielens-chart/chart/templates/ingress.yaml
  kubernetes/demo/movielens-chart/chart/templates/service.yaml
  kubernetes/demo/movielens-chart/chart/templates/serviceaccount.yaml
  kubernetes/demo/movielens-chart/chart/values.yaml
  kubernetes/serving-chart/README-CN.md
  kubernetes/serving-chart/README.md
  kubernetes/serving-chart/chart/.helmignore
  kubernetes/serving-chart/chart/Chart.yaml
  kubernetes/serving-chart/chart/templates/NOTES.txt
  kubernetes/serving-chart/chart/templates/_helpers.tpl
  kubernetes/serving-chart/chart/templates/hpa.yaml
  kubernetes/serving-chart/chart/templates/service.yaml
  kubernetes/serving-chart/chart/templates/serviceaccount.yaml
  kubernetes/serving-chart/chart/templates/statefulset.yaml
  kubernetes/serving-chart/chart/values.yaml
Labels: enhancement

#82 Implement twotowers dssm model
  demo/dataset/ml_1m/match_dataset_cf.py
  demo/dataset/ml_1m/match_dataset_negsample_10.yaml
  demo/twotowers/README-CN.md
  demo/twotowers/README.md
  demo/twotowers/baseline/conf/global_hot_ml_1m.yaml
  demo/twotowers/baseline/conf/item_cf_ml_1m.yaml
  demo/twotowers/baseline/conf/spark_als_ml_1m.yaml
  demo/twotowers/baseline/conf/swing_ml_1m.yaml
  demo/twotowers/baseline/global_hot.py
  demo/twotowers/baseline/item_cf.py
  demo/twotowers/baseline/log/global_hot_ml_1m.log
  demo/twotowers/baseline/log/item_cf_ml_1m.log
  demo/twotowers/baseline/log/spark_als_ml_1m.log
  demo/twotowers/baseline/log/swing_ml_1m.log
  demo/twotowers/baseline/spark_als.py
  demo/twotowers/baseline/swing.py
  demo/twotowers/dssm/conf/dssm_bce_neg100_ml_1m.yaml
  demo/twotowers/dssm/conf/dssm_bce_neg10_ml_1m.yaml
  demo/twotowers/dssm/dssm.py
  demo/twotowers/dssm/log/dssm_bce_neg100_ml_1m.log
  demo/twotowers/dssm/log/dssm_bce_neg10_ml_1m.log
  demo/twotowers/dssm/schema/ml_1m/item_column_schema
  demo/twotowers/dssm/schema/ml_1m/item_combine_schema
  demo/twotowers/dssm/schema/ml_1m/user_column_schema
  demo/twotowers/dssm/schema/ml_1m/user_combine_schema
  python/algos/__init__.py
  python/algos/dssm_net.py
Labels: enhancement

#86 [deployment] add jupyter docker file
  docker/ubuntu20.04/Dockerfile_codeserver
  docker/ubuntu20.04/Dockerfile_jupyter
  docker/ubuntu20.04/README-CN.md
  docker/ubuntu20.04/README.md
  docker/ubuntu20.04/jupyter-s6/cont-init.d/01-copy-tmp-home
  docker/ubuntu20.04/jupyter-s6/services.d/jupyterlab/run
Labels: enhancement

#91 Use ms.nn.Normalization instead of torch.nn.BatchNorm1d.
  python/algos/layers.py
Labels: bug

#95 Add python preprocessor
  CMakeLists.txt
  cmake/metaspore_serving.cmake
  cmake/metaspore_shared.cmake
  cmake/metaspore_tests.cmake
  cpp/metaspore/string_utils.h
  cpp/serving/arrow_tensor_serde.cpp
  cpp/serving/arrow_tensor_serde.h
  cpp/serving/converters.cpp
  cpp/serving/converters.h
  cpp/serving/grpc_model_runner.cpp
  cpp/serving/grpc_model_runner.h
  cpp/serving/grpc_server.cpp
  cpp/serving/model_manager.cpp
  cpp/serving/py_preprocessing_model.cpp
  cpp/serving/py_preprocessing_model.h
  cpp/serving/py_preprocessing_ort_model.cpp
  cpp/serving/py_preprocessing_ort_model.h
  cpp/serving/py_preprocessing_process.cpp
  cpp/serving/py_preprocessing_process.h
  cpp/serving/shared_grpc_context.cpp
  cpp/serving/shared_grpc_context.h
  cpp/serving/shared_grpc_server_builder.cpp
  cpp/serving/shared_grpc_server_builder.h
  cpp/tests/serving/py_preprocessing_model_test.cpp
  cpp/tests/serving/py_preprocessing_process_test.cpp
  python/scripts/preprocessing/example_preprocessor.py
  python/scripts/preprocessing/example_requirements.txt
  python/scripts/preprocessing/preprocessor_service.py
  python/scripts/preprocessing/test_example_preprocessor.py
  vcpkg.json
Labels: enhancement

#97 add consul_watch_load.py script
  cmake/metaspore_serving.cmake
  python/scripts/consul_watch_load.py
Labels: enhancement

#99 [serving][deployment] update serving docker
  .gitignore
  cmake/metaspore_serving.cmake
  docker/ubuntu20.04/Dockerfile_serving_build
  docker/ubuntu20.04/Dockerfile_serving_release
Labels: enhancement

#106 remove out dated files
  compile.sh
  docker/ubuntu20.04/compile.sh
  docker/ubuntu20.04/package.sh
  run_build.sh
  tutorials/metaspore-getting-started.ipynb
  tutorials/metaspore-tutorial.ipynb
Labels: enhancement

#104 add consul watch&load deployment on k8s
  cmake/metaspore_serving.cmake
  kubernetes/serving-chart/chart/templates/NOTES.txt
  kubernetes/serving-chart/chart/templates/statefulset.yaml
  kubernetes/serving-chart/chart/values.yaml
  python/scripts/consul/Dockerfile
  python/scripts/consul/build.sh
  python/scripts/consul/consul_watch_load.py
  python/scripts/consul/create_consul_watch.sh
Labels: enhancement

#107 Update MetaSpore tutorial
  tutorials/metaspore-getting-started.ipynb
Labels: bug

#109 support multiple model outputs
  python/metaspore/estimator.py
  python/metaspore/model.py
Labels: enhancement

#110 [deployment] add lakesoul to training image
  README-CN.md
  docker/ubuntu20.04/Dockerfile_jupyter
  docker/ubuntu20.04/Dockerfile_training_release
  docker/ubuntu20.04/jupyter-s6/services.d/jupyterlab/run
  docker/ubuntu20.04/release-copy-deps-pom.xml
Labels: enhancement

#114 Movielens demo notebooks for Alpha IDE
  demo/movielens/offline/notebooks/1-data_exploration.ipynb
  demo/movielens/offline/notebooks/1-data_exploration.yaml
  demo/movielens/offline/notebooks/2-ctr_prediction.ipynb
  demo/movielens/offline/notebooks/2-ctr_prediction.yaml
  demo/movielens/offline/notebooks/resources/split_data.png
  demo/movielens/offline/notebooks/schema/column_schema
  demo/movielens/offline/notebooks/schema/deep_combine_column_schema
  demo/movielens/offline/notebooks/schema/wide_combine_column_schema
Labels: MovieLens Demo

#112 [training] add adamw updater
  cpp/metaspore/dense_tensor.cpp
  cpp/metaspore/dense_tensor_partition.h
  cpp/metaspore/sparse_tensor.cpp
  cpp/metaspore/sparse_tensor_partition.h
  cpp/metaspore/tensor_partition_store.cpp
  python/metaspore/__init__.py
  python/metaspore/embedding.py
  python/metaspore/estimator.py
  python/metaspore/model.py
  python/metaspore/updater.py
Labels: enhancement

#116 [deployment] add spark docker file
  docker/ubuntu20.04/Dockerfile_spark_release
Labels: enhancement
